# fly.toml app configuration file generated for fso-nodejs-express on 2023-11-17T22:52:02+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "fso-nodejs-express"
primary_region = "waw"

[build]

[env]
  PORT = "3000"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
